### ISSUE TITLE
RPC protocol

### ISSUE THREAD

**Issue by dselivanov** [rstudio/sparkapi#1]
This is not a issue, but a quick note from my experience. 
IMHO SparkR RPC is the most terrible part of SparkR project. It incredibly slow and memory inefficient. **R <-> jvm** data transfer is so painful with sparkr RPC... ([here](http://dsnotes.com/articles/r-read-hdfs) I made some timings  for transfer of small `data.frame`)
Of course I don't have full information about goal of this package (but I think, main goal is to create foundation for dplyr backend ), but I'm not sure it is good idea to use it. Mb something that relies on `rJava` will be much better choice. Hope this may be useful. 
Also I will be happy to contribute when project will have roadmap.

**Comment by jjallaire** [comment]
Hi, thanks for the feedback!

The main idea right now is to define an API to abstract away the underlying
RPC implementation (so it can evolve, get faster, etc.). We are naturally
starting with what is already implemented but that in no way precludes
future improvements along the lines you suggest.


On Tue, Jun 21, 2016 at 6:12 AM, Dmitriy Selivanov <notifications@github.com

**Comment by dselivanov** [comment]
ok, good to know, closing...
