### ISSUE TITLE
spark_invoke errors not reported from log

### ISSUE THREAD

**Issue by kevinushey** [rstudio/sparkapi#3]
E.g.

```
> iris_tbl <- copy_to(sc, iris, "iris", overwrite = TRUE)
Error: Error: <unknown error>
```

However, I see in the logs (from `spark_log()`):

```
16/06/21 13:29:17 ERROR RBackendHandler: dropTempTable on 7 failed
```

Is this intended, or a regression caused during the refactor?

**Comment by jjallaire** [comment]
I just added the ability to register an unknown error handler with the
sparkapi package (which should scrape the logs). Could you try again w/
current master on both packages?

**Comment by kevinushey** [comment]
Can confirm that all is well now!
